//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFileOrganizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeFileOrganizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;categories&gt;
        ///  &lt;category name=&quot;Films&quot;&gt;
        ///    &lt;template temp=&quot;FilmInfo.xml&quot; folder=&quot;false&quot; file=&quot;true&quot;/&gt;
        ///    &lt;template temp=&quot;MyStatistics.xml&quot; folder=&quot;false&quot; file=&quot;true&quot;/&gt;
        ///  &lt;/category&gt;
        ///  &lt;category name=&quot;Serials&quot;&gt;
        ///    &lt;template temp=&quot;SerialInfo.xml&quot; folder=&quot;true&quot; file=&quot;true&quot;/&gt;
        ///    &lt;template temp=&quot;EpisodeInfo.xml&quot; folder=&quot;false&quot; file=&quot;true&quot;/&gt;
        ///    &lt;template temp=&quot;MyStatistics.xml&quot; folder=&quot;false&quot; file=&quot;true&quot;/&gt;
        ///  &lt;/category&gt;
        ///&lt;/categories&gt;.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;info&gt;
        ///  &lt;group name=&quot;Episode info&quot;&gt;
        ///    &lt;value name=&quot;Name EN&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Name CZ&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Original name&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///  &lt;/group&gt;
        ///&lt;/info&gt;.
        /// </summary>
        internal static string EpisodeInfo {
            get {
                return ResourceManager.GetString("EpisodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;info&gt;
        ///  &lt;group name=&quot;Film info&quot;&gt;
        ///    &lt;value name=&quot;Name EN&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Name CZ&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Name origin&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Release date&quot; type=&quot;date&quot; default=&quot;1/1/2000&quot;/&gt;
        ///    &lt;value name=&quot;IMDb&quot; type=&quot;link&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;CSFD&quot; type=&quot;link&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Rating&quot; type=&quot;rating&quot; default=&quot;3&quot;/&gt;
        ///    &lt;value name=&quot;Story&quot; type=&quot;multilin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilmInfo {
            get {
                return ResourceManager.GetString("FilmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;info&gt;
        ///  &lt;group name=&quot;Statistics&quot;&gt;
        ///    &lt;value name=&quot;Open&quot; type=&quot;counter&quot; default=&quot;0(1/1/2000)&quot;/&gt;
        ///  &lt;/group&gt;
        ///&lt;/info&gt;.
        /// </summary>
        internal static string MyStatistics {
            get {
                return ResourceManager.GetString("MyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;info&gt;
        ///  &lt;group name=&quot;Serial info&quot;&gt;
        ///    &lt;value name=&quot;Name EN&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Name CZ&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Name origin&quot; type=&quot;text&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Release date&quot; type=&quot;date&quot; default=&quot;1/1/2000&quot;/&gt;
        ///    &lt;value name=&quot;IMDb&quot; type=&quot;link&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;CSFD&quot; type=&quot;link&quot; default=&quot;none&quot;/&gt;
        ///    &lt;value name=&quot;Rating&quot; type=&quot;rating&quot; default=&quot;3&quot;/&gt;
        ///    &lt;value name=&quot;Story&quot; type=&quot;multil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SerialInfo {
            get {
                return ResourceManager.GetString("SerialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;info&gt;
        ///  &lt;group name=&quot;system&quot;&gt;
        ///    &lt;value name=&quot;name&quot; type=&quot;text&quot; default=&quot;&quot;/&gt;
        ///    &lt;value name=&quot;size&quot; type=&quot;byte&quot; default=&quot;0&quot;/&gt;
        ///    &lt;value name=&quot;last change&quot; type=&quot;date&quot; default=&quot;1/1/2000&quot;/&gt;
        ///    &lt;value name=&quot;creation&quot; type=&quot;date&quot; default=&quot;1/1/2000&quot;/&gt;
        ///  &lt;/group&gt;
        ///&lt;/info&gt;.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
    }
}
